apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_743dffb7237
          ports:
            - name: http
              containerPort: 8080
          
          