apiVersion: apps/v1
kind: Deployment
metadata:
  name: krampoline
spec:
  selector:
    matchLabels:
      app: krampoline
  template:
    metadata:
      labels:
        app: krampoline
    spec:
      containers:
        - name: krampoline
          # 여러분의 image 주소를 입력해주세요.
          image: 024e628baaf8bfbbf1491d6fd2ba2476c52d94e17b19cf4c2c0ef3790e48b941